package com.base;



/**
 * Child generated by MyEclipse - Hibernate Tools
 */

public class Child  implements java.io.Serializable {


    // Fields    

     private Integer sno;
     private Parent parent;
     private String childName;
     private String comment;
     private Integer version;


    // Constructors

    public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/** default constructor */
    public Child() {
    }

	/** minimal constructor */
    public Child(Integer sno, Parent parent) {
        this.sno = sno;
        this.parent = parent;
    }
    
    /** full constructor */
    public Child(Integer sno, Parent parent, String childName) {
        this.sno = sno;
        this.parent = parent;
        this.childName = childName;
    }

   
    // Property accessors

    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    public Parent getParent() {
        return this.parent;
    }
    
    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public String getChildName() {
        return this.childName;
    }
    
    public void setChildName(String childName) {
        this.childName = childName;
    }
   








}