package com.base;

import java.util.HashSet;
import java.util.Set;


/**
 * Parent generated by MyEclipse - Hibernate Tools
 */

public class Parent  implements java.io.Serializable {


    // Fields    

     private Integer sno;
     private String name;
     private String citi;
     private Set childs = new HashSet(0);
     private Long version;

    // Constructors

    /** default constructor */
    public Parent() {
    }

	/** minimal constructor */
    public Parent(Integer sno) {
        this.sno = sno;
    }
    
    /** full constructor */
    public Parent(Integer sno, String name, Set childs) {
        this.sno = sno;
        this.name = name;
        this.childs = childs;
    }

   
    // Property accessors

    public Integer getSno() {
        return this.sno;
    }
    
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getChilds() {
        return this.childs;
    }
    
    public void setChilds(Set childs) {
        this.childs = childs;
    }

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getCiti() {
		return citi;
	}

	public void setCiti(String citi) {
		this.citi = citi;
	}
   








}