package com.base;

/**
 * Rad generated by MyEclipse Persistence Tools
 */

public class Rad implements java.io.Serializable {

	// Fields

	private RadId id;

	private String name;
	
	private Integer version;

	// Constructors

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	/** default constructor */
	public Rad() {
	}

	/** minimal constructor */
	public Rad(RadId id) {
		this.id = id;
	}

	/** full constructor */
	public Rad(RadId id, String name) {
		this.id = id;
		this.name = name;
	}

	// Property accessors

	public RadId getId() {
		return this.id;
	}

	public void setId(RadId id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}