package com.base;

/**
 * RadId generated by MyEclipse Persistence Tools
 */

public class RadId implements java.io.Serializable {

	// Fields

	private Integer key1;

	private Integer key2;

	// Constructors

	/** default constructor */
	public RadId() {
	}

	/** full constructor */
	public RadId(Integer key1, Integer key2) {
		this.key1 = key1;
		this.key2 = key2;
	}

	// Property accessors

	public Integer getKey1() {
		return this.key1;
	}

	public void setKey1(Integer key1) {
		this.key1 = key1;
	}

	public Integer getKey2() {
		return this.key2;
	}

	public void setKey2(Integer key2) {
		this.key2 = key2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RadId))
			return false;
		RadId castOther = (RadId) other;

		return ((this.getKey1() == castOther.getKey1()) || (this.getKey1() != null
				&& castOther.getKey1() != null && this.getKey1().equals(
				castOther.getKey1())))
				&& ((this.getKey2() == castOther.getKey2()) || (this.getKey2() != null
						&& castOther.getKey2() != null && this.getKey2()
						.equals(castOther.getKey2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey1() == null ? 0 : this.getKey1().hashCode());
		result = 37 * result
				+ (getKey2() == null ? 0 : this.getKey2().hashCode());
		return result;
	}

}